name: RadioPlayer
options:
  createIntermediateGroups: true
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    PRODUCT_BUNDLE_IDENTIFIER: com.gaodacheng.RadioPlayer
    SWIFT_VERSION: 5.9

targets:
  RadioPlayer:
    type: application
    platform: iOS
    sources:
      - path: RadioPlayer/RadioPlayer
    info:
      path: RadioPlayer/RadioPlayer/Info.plist
      properties:
        CFBundleDisplayName: RadioPlayer
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UIBackgroundModes:
          - audio
    settings:
      base:
        INFOPLIST_FILE: RadioPlayer/RadioPlayer/Info.plist
        DEVELOPMENT_TEAM: HF9539F7A4
        CODE_SIGN_IDENTITY: iPhone Developer
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "0.1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
    scheme:
      testTargets:
        - RadioPlayerTests
  RadioPlayerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RadioPlayer/RadioPlayerTests
    dependencies:
      - target: RadioPlayer
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.gaodacheng.RadioPlayerTests
